/**
 * Loads the keyword glossary from the bundled `public/keywords.json` file.
 * That file is regenerated by GitHub Actions every 6 hours
 * (.github/workflows/update-keywords.yml) so the browser never hits the
 * wiki at runtime — no rate limits, no CORS, no extra latency.
 */

export type KeywordMap = Record<string, string>;

interface KeywordsFile {
  generatedAt: string;
  keywords: KeywordMap;
}

/** Loads the static glossary. Failure is silent ({} returned). */
export async function loadKeywordMap(): Promise<KeywordMap> {
  try {
    const url = `${import.meta.env.BASE_URL}keywords.json`;
    const r = await fetch(url, { cache: 'no-cache' });
    if (!r.ok) return {};
    const data = (await r.json()) as KeywordsFile;
    return data.keywords ?? {};
  } catch {
    return {};
  }
}
